const properties = [
  {
    id: 1,
    name: "Cozy Apartment",
    address: "123 Main St, Apt 4B",
    type: "Apartment",
    status: "Available",
    bedrooms: 2,
    bathrooms: 1,
    area: 80,
    price: 150000,
    image: "/img_1.jpg",
    checkIns: 12,
    checkOuts: 8,
  },
  {
    id: 2,
    name: "Modern House",
    address: "456 Elm St",
    type: "House",
    status: "Rented",
    bedrooms: 4,
    bathrooms: 3,
    area: 200,
    price: 300000,
    image: "/img_2.jpg",
    checkIns: 20,
    checkOuts: 18,
  },
  {
    id: 3,
    name: "Office Space",
    address: "789 Oak Ave, Suite 300",
    type: "Commercial",
    status: "Available",
    bedrooms: 0,
    bathrooms: 2,
    area: 350,
    price: 450000,
    image: "/img_3.jpg",
    checkIns: 5,
    checkOuts: 2,
  },
  {
    id: 4,
    name: "Luxury Apartment",
    address: "321 Broadway, Apt 10A",
    type: "Apartment",
    status: "Rented",
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    price: 200000,
    image: "/img_4.jpg",
    checkIns: 15,
    checkOuts: 10,
  },
  {
    id: 5,
    name: "Country Home",
    address: "987 Farm Road",
    type: "House",
    status: "Available",
    bedrooms: 5,
    bathrooms: 4,
    area: 400,
    price: 500000,
    image: "/img_5.jpg",
    checkIns: 8,
    checkOuts: 6,
  },
  {
    id: 6,
    name: "Retail Storefront",
    address: "567 Market St",
    type: "Commercial",
    status: "Rented",
    bedrooms: 0,
    bathrooms: 1,
    area: 150,
    price: 300000,
    image: "/img_6.jpg",
    checkIns: 10,
    checkOuts: 5,
  },
  {
    id: 7,
    name: "Suburban House",
    address: "111 Maple Lane",
    type: "House",
    status: "Available",
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    price: 250000,
    image: "/img_7.jpg",
    checkIns: 7,
    checkOuts: 4,
  },
  {
    id: 8,
    name: "Downtown Loft",
    address: "42 City Center",
    type: "Apartment",
    status: "Rented",
    bedrooms: 1,
    bathrooms: 1,
    area: 60,
    price: 120000,
    image: "/img_8.jpg",
    checkIns: 18,
    checkOuts: 15,
  },
  {
    id: 9,
    name: "Warehouse Space",
    address: "89 Industrial Blvd",
    type: "Commercial",
    status: "Available",
    bedrooms: 0,
    bathrooms: 1,
    area: 500,
    price: 400000,
    image: "/img_9.jpg",
    checkIns: 3,
    checkOuts: 1,
  },
  {
    id: 10,
    name: "Penthouse Suite",
    address: "1 Luxury Lane, Apt 30",
    type: "Apartment",
    status: "Available",
    bedrooms: 4,
    bathrooms: 3,
    area: 200,
    price: 800000,
    image: "/img_10.jpg",
    checkIns: 25,
    checkOuts: 20,
  },
  {
    id: 11,
    name: "Lake House",
    address: "22 Lakeside Drive",
    type: "House",
    status: "Rented",
    bedrooms: 5,
    bathrooms: 4,
    area: 350,
    price: 600000,
    image: "/img_11.jpg",
    checkIns: 12,
    checkOuts: 8,
  },
  {
    id: 12,
    name: "Downtown Office",
    address: "20 High Rise Ave, Suite 400",
    type: "Commercial",
    status: "Available",
    bedrooms: 0,
    bathrooms: 2,
    area: 300,
    price: 500000,
    image: "/img_12.jpg",
    checkIns: 6,
    checkOuts: 3,
  },
  {
    id: 13,
    name: "Mountain Cabin",
    address: "777 Alpine Road",
    type: "House",
    status: "Available",
    bedrooms: 3,
    bathrooms: 2,
    area: 150,
    price: 200000,
    image: "/img_13.jpg",
    checkIns: 4,
    checkOuts: 2,
  },
  {
    id: 14,
    name: "Studio Apartment",
    address: "50 Downtown Lane, Apt 5",
    type: "Apartment",
    status: "Rented",
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
    price: 80000,
    image: "/img_14.jpg",
    checkIns: 10,
    checkOuts: 7,
  },
  {
    id: 15,
    name: "Shopping Mall Space",
    address: "90 Mall Drive",
    type: "Commercial",
    status: "Rented",
    bedrooms: 0,
    bathrooms: 1,
    area: 600,
    price: 750000,
    image: "/img_15.jpg",
    checkIns: 8,
    checkOuts: 5,
  },
  {
    id: 16,
    name: "Beachfront Condo",
    address: "10 Ocean View Lane, Apt 12",
    type: "Apartment",
    status: "Available",
    bedrooms: 2,
    bathrooms: 2,
    area: 100,
    price: 300000,
    image: "/img_16.jpg",
    checkIns: 5,
    checkOuts: 4,
  },
  {
    id: 17,
    name: "Farmhouse",
    address: "77 Green Valley",
    type: "House",
    status: "Available",
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    price: 350000,
    image: "/img_17.jpg",
    checkIns: 7,
    checkOuts: 6,
  },
  {
    id: 18,
    name: "Corporate Office",
    address: "33 Business Blvd",
    type: "Commercial",
    status: "Available",
    bedrooms: 0,
    bathrooms: 3,
    area: 400,
    price: 700000,
    image: "/img_18.jpg",
    checkIns: 9,
    checkOuts: 5,
  },
  {
    id: 19,
    name: "Urban Loft",
    address: "23 City High Rise",
    type: "Apartment",
    status: "Rented",
    bedrooms: 2,
    bathrooms: 1,
    area: 90,
    price: 180000,
    image: "/img_19.jpg",
    checkIns: 15,
    checkOuts: 12,
  },
  {
    id: 20,
    name: "Luxury Villa",
    address: "100 Prestige Blvd",
    type: "House",
    status: "Rented",
    bedrooms: 6,
    bathrooms: 5,
    area: 500,
    price: 1000000,
    image: "/img_20.jpg",
    checkIns: 20,
    checkOuts: 18,
  },
];

export default properties;
